### ISSUE TITLE
Opencv version is not available!

### ISSUE THREAD

**Issue by lnxpy** [pycdr/WM#1]
I tried to install the default `requiremenets.txt` file but it brings up an error with the following title:
`ERROR: no matching distribution found for opencv-python==3.4.5.20`
I tried the last stable version of cv2 which is 4.5.1.48 and it did work well.
You may need to update the required packages,

**Comment by pycdr** [comment]
Hi @lnxpy !
thank to you, it is fixed now.
I guess other versions doesn't have problem with the program too, so I will add it to the TODO.md to be done with another work.
